# Generated by Django 4.1.2 on 2023-06-05 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipoProducto', models.AutoField(db_column='idTipoProducto', primary_key=True, serialize=False)),
                ('TipoProductos', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('nroSerie', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=20)),
                ('cantidadProducto', models.CharField(max_length=20)),
                ('id_producto', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='venta.tipoproducto')),
            ],
        ),
    ]
