# Generated by Django 4.1.2 on 2023-06-08 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='id_producto',
        ),
        migrations.AddField(
            model_name='productos',
            name='activo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productos',
            name='descProducto',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='productos',
            name='id_tipoProducto',
            field=models.ForeignKey(db_column='idTipoProducto', default='', on_delete=django.db.models.deletion.CASCADE, to='venta.tipoproducto'),
        ),
        migrations.AddField(
            model_name='productos',
            name='precioProducto',
            field=models.CharField(default='', max_length=20),
        ),
    ]
